import jsPDF from "jspdf";

export function downloadReport(
  atsScore: number,
  extractedSkills: string[],
  missingSkills: string[],
  recommendations: string[],
  suggestions: string[]
) {
  const doc = new jsPDF();

  let y = 20;

  function checkPage() {
    if (y > 270) {
      doc.addPage();
      y = 20;

      doc.setFontSize(10);
      doc.text(
        "Generated by CareerPilot AI",
        20,
        285
      );
    }
  }

  // Title
  doc.setFontSize(22);
  doc.text(
    "CareerPilot Resume Report",
    20,
    y
  );

  y += 12;

  // Date
  doc.setFontSize(10);
  doc.text(
    `Generated on: ${new Date().toLocaleDateString()}`,
    20,
    y
  );

  y += 20;

  // ATS Score
  doc.setFontSize(16);
  doc.text("ATS Score", 20, y);

  y += 12;

  doc.setTextColor(0, 102, 255);
  doc.setFontSize(24);
  doc.text(`${atsScore}%`, 20, y);

  doc.setTextColor(0, 0, 0);

  y += 25;

  // Skills Found
  doc.setFontSize(16);
  doc.text("Skills Found", 20, y);

  y += 12;

  extractedSkills.forEach((skill) => {
    checkPage();

    doc.setFontSize(12);
    doc.text(`• ${skill}`, 30, y);

    y += 10;
  });

  y += 10;

  // Missing Skills
  checkPage();

  doc.setFontSize(16);
  doc.text("Missing Skills", 20, y);

  y += 12;

  missingSkills.forEach((skill) => {
    checkPage();

    doc.setFontSize(12);
    doc.text(`• ${skill}`, 30, y);

    y += 10;
  });

  y += 10;

  // AI Recommendations
  checkPage();

  doc.setFontSize(16);
  doc.text(
    "AI Recommendations",
    20,
    y
  );

  y += 12;

  recommendations.forEach((item) => {
    checkPage();

    const lines =
      doc.splitTextToSize(
        `• ${item}`,
        160
      );

    doc.setFontSize(12);
    doc.text(lines, 30, y);

    y += lines.length * 8;
  });

  y += 10;

  // Resume Suggestions
  checkPage();

  doc.setFontSize(16);
  doc.text(
    "Resume Suggestions",
    20,
    y
  );

  y += 12;

  suggestions.forEach((item) => {
    checkPage();

    const lines =
      doc.splitTextToSize(
        `• ${item}`,
        160
      );

    doc.setFontSize(12);
    doc.text(lines, 30, y);

    y += lines.length * 8;
  });

  // Footer
  doc.setFontSize(10);
  doc.text(
    "Generated by CareerPilot AI",
    20,
    285
  );

  doc.save(
    "CareerPilot-Report.pdf"
  );
}